version: 'test-{build}'
environment:
  matrix:
    - nodejs_version: '6'
    - nodejs_version: '8'
    - nodejs_version: '10'
platform:
  - x86
  - x64
clone_folder: 'c:\projects\%APPVEYOR_PROJECT_NAME%'
install:
  - ps: 'Install-Product node $env:nodejs_version $env:platform'
  - 'appveyor DownloadFile https://github.com/Apollon77/SupportingFiles/raw/master/appveyor/bonjour/bonjourcore2.msi'
  - msiexec /i bonjourcore2.msi /qn
  - del bonjourcore2.msi
  - 'appveyor DownloadFile https://github.com/Apollon77/SupportingFiles/raw/master/appveyor/bonjour/bonjoursdksetup.exe'
  - bonjoursdksetup.exe /quiet
  - del bonjoursdksetup.exe
  - 'set BONJOUR_SDK_HOME=C:\Program Files\Bonjour SDK'
  - npm install
  - npm install homebridge-http-webhooks
  - npm install homebridge-sun-position
test_script:
  - node --version
  - npm --version
  - npm test
build: 'off'
